import { EMAIL_MESSAGE_ID_DOMAIN } from "../../config.js";

/**
 * Deterministic per-reply Message-ID, generated by us rather than left to the
 * SMTP driver. This is written to the DB before the send happens (see
 * jobs/sendEmail.ts) so threading survives a lost SMTP response, and a pg-boss
 * retry reuses the same ID instead of forking the thread.
 */
export function buildOutboundMessageId(
  replyId: string,
  domain: string = EMAIL_MESSAGE_ID_DOMAIN,
): string {
  return `<reply.${replyId}@${domain}>`;
}
