apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: helpdesk

servers: 1
agents: 2

image: docker.io/rancher/k3s:v1.36.3-k3s1

registries:
  create:
    name: helpdesk-registry
    host: "0.0.0.0"
    hostPort: "5111"

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: 180s

  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
